//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
